global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'zeus'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.1.75:9100']
  
  - job_name: 'poseidon'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.1.76:9100']
  
  - job_name: 'ares'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.1.77:9100']
